### ISSUE TITLE
Symfony4

### ISSUE THREAD

**Issue by pugromagna** [pugromagna/eventi#1]

**Comment by Fuminshou** [comment]
@sensorario tu o Ale riuscite a farmi avere l'abstract per l'evento del 6?
*grazie*

**Comment by AlessandroMinoccheri** [comment]
Symfony 4 represents a rethinking of its ideas and features from the ground up to match the industry practices: application bundles are gone, config parameters are now environment variables, the application directory structure is easier to navigate and hundreds of other small improvements that will make you love Symfony.

The result is less Symfony concepts and more standard practices. Easier to learn, easier to configure, easier to install and deploy and easier to master. Simple, powerful, amazing!

**Comment by sensorario** [comment]
@AlessandroMinoccheri manca solo un po' di materiale da aggiungere a questo repo e poi possiamo chiudere la issue ^_^

**Comment by quanton81** [comment]
@AlessandroMinoccheri Ciao Alessandro, aggiungerai anche il codice di esempio?

**Comment by AlessandroMinoccheri** [comment]
Si a breve aggiungerò anche il codice di esempio

**Comment by AlessandroMinoccheri** [comment]
Ho aggiunto nel readme il link al codice che ho caricato su github @quanton81
