### ISSUE TITLE
CQRS in PHP

### ISSUE THREAD

**Issue by kevincittadini** [pugromagna/eventi#13]
Potrebbe essere istruttivo spiegare il pattern, come si differenzia da un classico approccio CRUD e, cosa più importante, come poterlo applicare in PHP magari mostrando qualche caso d'uso o esempio pratico.

**Comment by ricfrank** [comment]
@kevincittadini ciao. 

Io ho proposto questo https://github.com/DevRomagna/eventi/issues/70 al dev romagna. Volendo lo potrei fare anche al pug.

Ti volevi proporre come speaker oppure ti interessa l'argomento e vorresti che venisse trattato al pug ?

**Comment by kevincittadini** [comment]
@ricfrank Ciao :) Sì, avevo visto la tua proposta nel DevRomagna. Io non mi propongo come speaker ma mi interessa molto l'argomento. Mi farebbe piacere lo tenessi tu.

**Comment by Fuminshou** [comment]
Martedì 11 settembre a Cesena (ideato o dinamo cowork)
speaker @ricfrank 

attendo bio e abstract del talk

**Comment by AlessandroMinoccheri** [comment]
Perfetto!

**Comment by AlessandroMinoccheri** [comment]
@ricfrank riesci a caricare qualcosa su questo repository riguardante l'evento che dopo chiudiamo la issue?
Grazie

**Comment by sensorario** [comment]
Prego
