### ISSUE TITLE
Scrivere la propria libreria open source in php

### ISSUE THREAD

**Issue by sensorario** [pugromagna/eventi#24]
Vediamo insieme come fare per scrivere **codice da riusare** su tanti propri progetti **senza dover ricorrere al copia incolla**. In una sessione totalmente live vorrei creare insieme una semplice libreria sfruttando i mezzi a disposizione di php oggi. Vedremo insieme cose come:

 - creare un progetto (*hello world*) da zero
 - renderlo pubblico
 - sfruttare github per dare suggerimenti ai collaboratori (colleghi)
 - come tenere traccia degli aggiornamenti e delle operazioni da fare in caso di cambio di versione
 - come assegnare la versione corretta ad una libreria condivisa
 - scrivere codice con uno standard condiviso dalla community
 - contribuire effettivamente al progetto
 - usare strumenti online per verificare la qualita' del codice

**Comment by Fuminshou** [comment]
@sensorario possiamo organizzarlo per inizio ottobre?
Sarebbe martedì 2 ma valutiamo se posticipare di una settimana.

**Comment by sensorario** [comment]
@Fuminshou proviamo a mettere due date cosi ho modo di organizzarmi ^_^

**Comment by Fuminshou** [comment]
Appunto martedì 2 o martedì 10.
Altrimenti cambiamo giorno della settimana, tu quando saresti comodo @sensorario ?

**Comment by sensorario** [comment]
Il 10 e' un mercoledi, .... Per me OK il 2 ed il 9 ottobre.

**Comment by Fuminshou** [comment]
@sensorario per lo spazio? MADO può ospitare o dobbiamo cercare altro?

**Comment by AlessandroMinoccheri** [comment]
Mado può ospitare

**Comment by Fuminshou** [comment]
allora @AlessandroMinoccheri @sensorario decidete voi quando vi sta comodo e fatemi sapere:
• titolo
• abstract
• bio dello speaker

io non ci sono in nessuna delle due date quindi scegliete liberamente e confermatemi anche quella info.

Grazie
