### ISSUE TITLE
Docker e Php

### ISSUE THREAD

**Issue by quanton81** [pugromagna/eventi#30]

**Comment by matiux** [comment]
Non sono un espertone Docker ma sviluppo quotidianamente con un ambiente LEMP basato su docker (fatto da zero e basato su Debian buster) + PhpStorm + Xdebug. Quindi posso raccontarvi 2 cose volentieri

**Comment by AlessandroMinoccheri** [comment]
Potremmo fare anche una raccolta di varie esperienze tra di noi cosi ognuno potrebbe spiegare il proprio asset con i rispettivi pro e contro

**Comment by matiux** [comment]
Una tavola rotonda, a me piace come idea
Sto sistemando qualche container proprio ora :grin:

**Comment by sensorario** [comment]
sarebbe bello avere un container del pug, open source
