### ISSUE TITLE
Symfony e Domain Driven Design

### ISSUE THREAD

**Issue by matiux** [pugromagna/eventi#31]
Ciao, so che il PUG è in ferie fino a settembre ma mi piacerebbe proporre una serata, magari per ora "informale" (ma con l'idea di rifarla, migliorata e ufficiale dopo l'estate) per condividere con voi il modo in cui sviluppo e basato su alcuni concetti del DDD. 

Da quando cerco di seguire la filosofia DDD mi sono accorto di quanto il framework sia, a mio avviso, ininfluente se ci si concentra sul Dominio.

Mi piacerebbe quindi, senza slide, ma con pc e codice alla mano, partire da zero e modellare qualcosa insieme, ad esempio un utente, a livello di dominio fino a renderlo persistibile su database.

Gli argomenti che ne verrebbero fuori sono:

- TDD con phpunit
- Hexagonal pattern (chiamato anche port and adapter)
- DDD con i suoi tre layers (Dominio, Applicazione e Infrastruttura)

Il tutto, una volta arrivati nel layer di infrastruttura, gestito con Doctrine e Symfony. (v3.4 ma se qualcuno mi supporta probabilmente possiamo usare anche la 4)

Dato che le cose sono tante propongo un venerdì sera, (magari con pizza?) così da avere più flessibilità di orario.

Per la location Rimini è disponibile, ma vediamo dove eventualmente è più comodo per tutti.

**Comment by DonCallisto** [comment]
Rimini mi piace 😋

**Comment by AlessandroMinoccheri** [comment]
Sarebbe molto interessante!

**Comment by sensorario** [comment]
https://github.com/frameworkless-movement/manifesto

**Comment by matiux** [comment]
@DonCallisto allora sarai dei nostri? :D

**Comment by DonCallisto** [comment]
@matiux A Rimini mi rimane sicuramente molto più comodo che Cesena o (peggio) Ravenna. Infatti non sono mai riuscito a venire per questa motivazione

**Comment by matiux** [comment]
Splendido @DonCallisto.
Vediamo se qualcun altro esprime interesse.
Poi iniziamo a buttare giù qualche data. Secondo me già 4-5 siamo sicuramente

**Comment by matiux** [comment]
Ciao a tutti,
anche se pochi proverei a proporre qualche possibile data.
Come dicevamo è una serata informale quindi la prendiamo con calma e anche se non siamo tantissimi vediamo comunque ne se esce qualcosa di interessante.

Si diceva di fare un venerdì sera per avere un po' di tempo in più.
Alcuni venerdì, almeno per me, buoni:
22 giugno
29 giugno
6 luglio

Che ne dite?

**Comment by DonCallisto** [comment]
Io il 22 non riesco, il 29 probabilmente sì. Il 6 è troppo avanti per poter decidere ora 😄

**Comment by AlessandroMinoccheri** [comment]
Il 29 potrebbe essere buono anche per me per ora

**Comment by matiux** [comment]
Allora per ora proviamo a concentrarci su venerdì 29 giugno!

**Comment by micc83** [comment]
Ciao @matiux, puoi contare anche me.

**Comment by DonCallisto** [comment]
Io purtroppo il 29 Giugno non potrò più venire (credo). Vi aggiorno.

**Comment by matiux** [comment]
@DonCallisto :(

**Comment by matiux** [comment]
@DonCallisto se invece di venerdì 29 facessimo venerdì 06 luglio, ti andrebbe meglio o sei comunque in forse?

**Comment by DonCallisto** [comment]
Mi rimane sempre un po' difficile stabilire con così tanto anticipo il mio calendario. Quindi per me è sempre un forse. Comunque non dovete mica basare l'evento sul fatto che io riesca a venire o meno 😄

**Comment by matiux** [comment]
Direi di provare e vedere cosa ne esce.
Se siete tutti d'accordo chiederei a @Fuminshou (sei dei nostri?) di programmare l'evento su meetup per venerdì 29 giugno.
Alle 20:00 può andare bene?
Io sono li già da prima quindi se qualcuno vuole mangiare qualcosa insieme mi trova.

Indirizzo location: Viale Principe Amedeo 7 - 47900 Rimini (RN). In pratica è dentro al grattacielo.

I parcheggi li in torno sono tutti a pagamento e non ricordo fino a che ora. Nel caso in cui si pagasse anche dopo le 20 vi consiglio di parcheggiare in Via Sinistra del Porto che è a 4 minuti a piedi dal grattacielo. è una stradina che costeggia il canale e si può parcheggiare senza problemi.

**Comment by Fuminshou** [comment]
Ecco l'evento su meetup https://www.meetup.com/it-IT/PUG-Romagna-PHP-User-Group-Romagnolo/events/252150287/

**Comment by AlessandroMinoccheri** [comment]
@matiux hai del materiale da caricare dell'evento passato?

**Comment by matiux** [comment]
Ciao @AlessandroMinoccheri 
Slide non ne ho fatte. ho un documento con un po' di appunti sull'Hexagonal architecture che volendo posso caricare da qualche parte

Qui c'è un esempio di refactoring in 4 step per mostrare un po' l'architettura esagonale:
https://github.com/matiux/PhpDesignPatterns/tree/master/ExagonalArchitecture

E qui un esempio del tutto accademico per mostrare un po' di concetti del DDD
https://github.com/matiux/UtenteDDDExample

**Comment by AlessandroMinoccheri** [comment]
Io farei una pull request con l'evento dove magari metti un pò di documentazione o link esterni degli argomenti trattati, che ne pensi @matiux
