### ISSUE TITLE
Architettura esagonale

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [pugromagna/eventi#34]
L'architettura esagonale, Anche conosciuta come pattern “Ports and Adapters” di Alistar Cockburn, ha lo scopo di centralizzare l’attenzione sull’applicazione e decentralizzare tutti i sistemi esterni.
E' un buon modo per strutturare un'applicazione e proteggere il modello di dominio dai sistemi esterni disaccoppiando il framework dal dominio

**Comment by matiux** [comment]
@AlessandroMinoccheri ti proponi anche come speaker? Diversamente 2 parole posso spenderle volentieri.

Location a Rimini disponibile.

**Comment by AlessandroMinoccheri** [comment]
@matiux sarebbe bello sentirti come speaker!

**Comment by matiux** [comment]
Se nasce interesse per l'argomento provo ad organizzarmi!

**Comment by AlessandroMinoccheri** [comment]
@matiux appena puoi magari metti qui qualche link dei repository / slide / codice di ieri sera cosi poi chiudiamo questa issue.
Grazie

**Comment by matiux** [comment]
Materiale della serata aggiunto

https://github.com/pugromagna/eventi/tree/master/20181106-hexagonal-architecture
