### ISSUE TITLE
Async - Event Driven programming

### ISSUE THREAD

**Issue by sensorario** [pugromagna/eventi#36]
"Mentre in un programma tradizionale l'esecuzione delle istruzioni segue percorsi fissi, che si ramificano soltanto in punti ben determinati predefiniti dal programmatore, nei programmi scritti utilizzando la tecnica a eventi il flusso del programma è largamente determinato dal verificarsi di eventi esterni." - Wikipedia

Mentre sto preparando un articolo per li blog di mado, ho pensando che sarebbe bello condividere nel PUG eventuali esperienze di event-driven programming.

**Comment by matiux** [comment]
Ciao @sensorario la tua proposta riguarda l'async programming, ad esempio con framework tipo Swoole? Se si non duplico la issue. Diversamente ne apro un'altra

**Comment by matiux** [comment]
Mi sono sentito con @sensorario fuori da gitub e l'argomento e lo stesso. Ci piacerebbe approfondire la programmazione asincrona in php. Qualcun'altro interessato?

**Comment by Fuminshou** [comment]
Abbiamo scelto di parlare di Swoole, evento programmato il 5/05/2020: https://www.meetup.com/it-IT/PUG-Romagna-PHP-User-Group-Romagnolo/events/268796343/
