### ISSUE TITLE
PHP 7.4 novitá 

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [pugromagna/eventi#49]

**Comment by AlessandroMinoccheri** [comment]
@matiux riesci a caricare del materiale in merito cosi dopo chiudiamo la issue? 
Grazie

**Comment by matiux** [comment]
Vedo di fare in giornata!

**Comment by matiux** [comment]
Fatto:
https://github.com/pugromagna/eventi/tree/master/20200205-php-7.4
