### ISSUE TITLE
Oltre il modello relazionale

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [pugromagna/eventi#51]
Talk divulgativo sull’evoluzione dei sistemi database nel corso negli anni, dalla nascita del modello relazionale fino alla definizione di nuovi modelli per la gestione di dati non strutturati ed esecuzione di elaborazioni dati parallele; in particolare vedremo insieme:
- Proprietà e limiti modello relazionale
- Big Data, Google e Hadoop
- Sharding, Amazon e NoSQL
- Database documentali
- Database a grafo
- Database orientati alle colonne
- Database In-Memory

**Comment by camillinif** [comment]
Ho caricato in questo [repository](https://github.com/camillinif/presentation-oltre-il-modello-relazionale) il materiale esempio utilizzato durante il talk

**Comment by AlessandroMinoccheri** [comment]
Perfetto! Grazie
