### ISSUE TITLE
OAuth 2.0: An introduction

### ISSUE THREAD

**Issue by DonCallisto** [pugromagna/eventi#52]
Visto che la serata si è già svolta, mi limito a pubblicare il link alle slide che ho appena pubblicato

https://speakerdeck.com/doncallisto/oauth2

**Comment by matiux** [comment]
@DonCallisto riesci a fare un PR con il materiale o quantomeno un readme con il link?

**Comment by DonCallisto** [comment]
Sì, scusami, non avevo notato che c'erano delle cartelle per ogni evento. A breve lo faccio.

**Comment by DonCallisto** [comment]
Chiusa in favore di https://github.com/pugromagna/eventi/pull/53
