### ISSUE TITLE
Deploy applicazioni php con pipeline (gitlab/bitbucket) e deployer php

### ISSUE THREAD

**Issue by giuseppemorelli** [pugromagna/eventi#54]
Vorrei proporre una serata su come effettuare un deploy o in generale impostare un sistema di Continuous Integration / Continuous Delivery con le pipeline di bitbucket e gitlab.

Il tipo di applicazione è indifferente, gli esempi potranno spaziare da laravel a e-commerce Magento.

Mi propongo come speaker per la serata, la location (mio ufficio) può contenere al max 7-8 persone quindi in caso di "alta affluenza" non ci stiamo fisicamente.
Chiedo aiuto per la location ai ragazzi/e del pug ( @matiux )

Ps. 
C'è una issue nel dev romagna ma è del 2017 e sembra essere "ferma".
https://github.com/DevRomagna/eventi/issues/65

**Comment by AlessandroMinoccheri** [comment]
Ciao Giuseppe, per questo evento ti vorresti proporre come speaker quindi? 
Mi sembra un ottimo argomento!

**Comment by matiux** [comment]
@giuseppemorelli le location di Rimini e Faenza sono sempre disponibili, o almeno su queste 2 posso dirlo senza grossi problemi.

**Comment by AlessandroMinoccheri** [comment]
Anche su Cesena la location direi che àe disponibile

**Comment by giuseppemorelli** [comment]
> Dove sarebbe la location?

@AlessandroMinoccheri il mio ufficio è a Riccione

**Comment by giuseppemorelli** [comment]
Domanda per @matiux : che software usi per fare le slide? 
es. https://github.com/matiux/matiux.github.io/tree/master/slides/php74
Thanks

**Comment by matiux** [comment]
@giuseppemorelli uso slides.com

**Comment by AlessandroMinoccheri** [comment]
Ciao @giuseppemorelli per i primi di Aprile (primo martedi/mercoledi del mese) vorresti portare questo talk? 
Come sedi valutiamo se Rimini possa andare bene oppure proviamone anche un'altra ma in quella zona direi.
Che ne pensi?

**Comment by giuseppemorelli** [comment]
Ciao @AlessandroMinoccheri ,
per me va bene per fare il talk ad Aprile. Ho già iniziato a preparare le slides.
Come sede (per questo talk) ci offre la sala riunioni il [master coworking](https://www.mastercoworking.org/) di Rimini se vogliamo (tempo fa avevo una scrivania condivisa li).

E' vicino al centro comerciale le Befane e nella loro sala riunioni direi che in 15-20 ci dovremmo stare.
Se invece ci sono molte persone da zona Faenza/Ravenna allora proverei con Cesena.

**Comment by Fuminshou** [comment]
Ciao @giuseppemorelli, gli spazi di Cesena e Faenza hanno più o meno la stessa capienza del coworking che ci hai indicato. Se dovesse esserci molta affluenza possiamo valutare di riproporre la serata prossimamente (se avrai voglia!)

Puoi farci avere le seguenti info così pubblichiamo l'evento su meetup?
- Nome Cognome e tua bio
- Titolo del talk
- Abstract del talk
- Eventuali info utili per i partecipanti (es: portare il pc perchè il talk prevede esercizi pratici)

Grazie mille!

**Comment by giuseppemorelli** [comment]
Ciao @Fuminshou @AlessandroMinoccheri ,
per favore riuscite a mettere le varie label alla issue così da evidenziare il discorso "evento programmato", speaker etc.?
Grazie

**Comment by AlessandroMinoccheri** [comment]
fatto

**Comment by giuseppemorelli** [comment]
Riferimenti dell'evento

Slides: https://www.slideshare.net/GiuseppeMorelli2/pug-romagna-pipeline-deployer-php

Demo: https://github.com/giuseppemorelli/pipeline-deployer-demo-pugromagna
