### ISSUE TITLE
Grav CMS - vantaggi/svantaggi

### ISSUE THREAD

**Issue by giuseppemorelli** [pugromagna/eventi#56]
Grav è un CMS flat-file quindi senza database basato su librerie symfony e twig come sistema di templating.
In un mondo dove Wordpress fa da padrone è interessante capire come una community come quella di Grav sia cresciuta esponenzialmente in circa 4 anni.

Mi propongo come speaker per condividere la mia esperienza di questo cms (il mio blog è fatto in Grav) e parlare principalmente di questi argomenti:
- cms flat vs cms "classici"
- cms flat vs cms headless
- pwa -> ne abbiamo davvero bisogno in alcuni casi?
- caratteristiche, vantaggi e svantaggi di Grav CMS

**Comment by AlessandroMinoccheri** [comment]
@giuseppemorelli riusciresti a fare una PR con del materiale dell'evento passato? 
Link, slide, quello che ritieni opportuno.

Grazie.

**Comment by giuseppemorelli** [comment]
@AlessandroMinoccheri inviata ora :)

Riporto il link delle slides anche qui come copia aggiuntiva:

https://www.slideshare.net/GiuseppeMorelli2/pug-romagna-grav-cms

**Comment by AlessandroMinoccheri** [comment]
Grazie!
