### ISSUE TITLE
Laravel Zero: per progetti "console-only"

### ISSUE THREAD

**Issue by giuseppemorelli** [pugromagna/eventi#57]
Domanda: come fare piccoli middleware per integrazioni con PHP?

Agli inizi c'era Silex, ora con Symfony 4 e 5 il progetto è stato abbandonato.
C'è ancora Slim PHP ma di fatto rimane un micro framework come Silex sulla quale bisogna lavorarci un po' se si vuole aggiungere un sistema di config file (per esempio)
Inizializzare un progetto intero con Symfony o Laravel mi sembra eccessivo (ma non impossibile).

Ho trovato questo: Laravel Zero: https://github.com/laravel-zero/laravel-zero

Ad oggi non l'ho mai provato ma solo "visto" e sembra però apprezzato dalla community.
Lo inizierò ad usare nei prossimi progetti ma se qualcuno ha già avuto esperienza e la vuole condividere sarei ben contento di ascoltarlo

Grazie a tutti

**Comment by giuseppemorelli** [comment]
Direi che dopo il PHP Day PUG edition questa issue non so se vale la pena lasciarla aperta.
Video dell'evento: https://www.youtube.com/watch?v=NQCkMkiB-s4

**Comment by AlessandroMinoccheri** [comment]
ok chiudiamo e nel caso ne apriamo un' altra se ne sentiamo la necessità!
Grazie.
