### ISSUE TITLE
Sindrome dell'impostore, motivazione nel lavoro e nella vita.

### ISSUE THREAD

**Issue by unrealmanu** [pugromagna/eventi#63]
E' ancora oggi un tabù parlare del proprio stato emotivo sul posto di lavoro? 
C'è chi crede che sia penalizzante o pericoloso mostrare punti di debolezza nel proprio habitat lavorativo.
Penso che invece, sia salutare, per se e per il team, confrontarsi, sostenersi, condividere le difficoltà, nello specifico vorrei affrontare alcuni temi, come la Sindrome dell'impostore, in piccola parte l'effetto Dunning-Kruger, ma sopratutto come superare i problemi cercando di migliorare lo stato di motivazione.

**Comment by AlessandroMinoccheri** [comment]
Molto interessante come argomento, possiamo metterti giá come speaker cosi sappiamo che dobbiamo solo trovare la data giusta @unrealmanu ?

**Comment by unrealmanu** [comment]
> Molto interessante come argomento, possiamo metterti giá come speaker cosi sappiamo che dobbiamo solo trovare la data giusta @unrealmanu ?

Certo che potete già inserirmi come speaker :) poi per la data, ci organizziamo

**Comment by mloru** [comment]
Mi accodo agli interessati 🙂

**Comment by AlessandroMinoccheri** [comment]
Potresti essere disponibile per l'1 Settembre @unrealmanu ?
Quanto duro circa il talk?

**Comment by unrealmanu** [comment]
Per il 1 settembre va bene, il talk durerà circa 40 minuti, è però un tempo indicativo perché sto revisionando il materiale a riguardo.

**Comment by AlessandroMinoccheri** [comment]
Potrebbe essere un problema per te se dopo il tuo ci fosse un talk riguardante l'ansia per gli sviluppatori @unrealmanu ?

**Comment by unrealmanu** [comment]
No no assolutamente, anzi è un argomento interessante :)
Parlo anche io un po' di ansia, di come aumeti a volte i sintomi della sindrome

**Comment by AlessandroMinoccheri** [comment]
Ottimo :) 
Grazie.

**Comment by AlessandroMinoccheri** [comment]
Potresti appena puoi mandare la tua bio e l'abstract del talk?
Cosi prepariamo l'evento da condividere.

**Comment by Fuminshou** [comment]
Ciao @unrealmanu,
mi sto occupando di creare l'evento di settembre, e sono anche la speaker del secondo talk
Ti ho scritto sullo slack del grusp per coordinarci, fammi sapere quando puoi 😃

**Comment by Fuminshou** [comment]
Slide e video pubblicati!
