### ISSUE TITLE
Laravel & Multi-Tenancy

### ISSUE THREAD

**Issue by oniz93** [pugromagna/eventi#65]
Ripropongo il topic di apertura del Laracon2020 con le mie esperienze fatte su un SAAS sviluppato con Laravel e YugaByte (un postgres modificato)

**Comment by Fuminshou** [comment]
@oniz93 ricordati di fare una PR con le slide ed eventuale altro materiale ;)

**Comment by oniz93** [comment]
#69 Slide del talk
