### ISSUE TITLE
Stop Mocking Everything

### ISSUE THREAD

**Issue by DonCallisto** [pugromagna/eventi#68]
A seguito del mio prossimo talk, che si terrà nell'ambito del SymfonyDay Italy 2020 Virtual Edition (https://2020.sfday.it/talks.html#samuele-lilli) e che sarà interamente in inglese, ho pensato che il suddetto talk possa essere proposto anche in questo ambito del PUGRomagna.
Se volete, dopo il 20 Novembre, possiamo programmare una serata in italiano sullo stesso tema e con lo stesso talk, magari in forma integrale (cosa che non riuscirò a fare all'internod el SFDay, avendo una slot di tempo limitata).

**Comment by AlessandroMinoccheri** [comment]
Ciao @DonCallisto potresti gentilmente aggiungere qui l'abstract ? 
Nel caso aggiungi anche la tua bio se vuoi!
Grazie.

**Comment by DonCallisto** [comment]
Abstract

Sempre più sviluppatori adottano la pratica del TDD, ma il codice da testare ed il codice di test sono troppo spesso in relazione uno a uno. Questo significa che ogni cambiamento che avviene sul codice, si riflette necessariamente in un conseguente cambiamento dei test unitari. La causa più probabile? L'abuso di test doubles (mocks, stub, ecc).
In questo talk ci concentreremo sulle metodologie e non sui tool di TDD utilizzati.
Non userò slide, solo codice PHP.
Costruirò un esempio pratico utilizzando sia PHPUnit sia PHPSpec, che sono i due tool principali per il TDD in PHP, cercando di mettere in luce i vantaggi di utilizzare implementazioni reali (quando possibile) invece che test doubles.

Bio

Mi chiamo Samuele Lilli e sono uno sviluppatore backend da ormai dieci anni. Attualmente lavoro presso Madisoft dove ci impegniamo, giorno dopo giorno, a rendere il comparto scuola migliore attraverso il nostro SaaS Nuvola.
Sono fortemente appassionato di tutto ciò che riguarda il buon design, il codice pulito, il testing e l'open source.
Di tanto in tanto partecipo come speaker a eventi di PUG locali e conferenze nazionali.

**Comment by AlessandroMinoccheri** [comment]
@DonCallisto Potresti mettere anche qui i riferimenti che hai citato nel talk e il repository? Nel caso puoi anche aprire una PR con una semplice lista del materiale utile.

Grazie.

**Comment by DonCallisto** [comment]
@AlessandroMinoccheri https://github.com/pugromagna/eventi/pull/75

**Comment by AlessandroMinoccheri** [comment]
Grazie!
